language: ruby

os:
  - linux
dist:
  - focal

rvm: 3
script:
- gem update --system
- gem install bundler
- bundler update --bundler
- gem install jekyll bundler
- JEKYLL_ENV=production bundle exec jekyll build --verbose

deploy:
  edge: true
  provider: firebase
  token:
    secure: "cByUMD1f1J8ISWdtalTtNu2btsDPfsFh75Mba8GjfZCPjqGuyDmmoTN77G437Kw450cvkUiCF3O4kfhCbXb/z6QV3/QQnsmOd82snVETpKQdLm+QUKq36kIbyADGH9s0ytRpcqQXlfe8EzAtBcxQsMb9MFXtr1kuZIfDmLnNr8FQ6wlY1vO4BNsvapW0Ys6bfJa/+XjqGE320rASd5u2Qj/7LgRyUZucVVMah47dpBgKe812z7DRspV3Xf5wGIbyWHIt9gvc+3xDiChdw35FBWiJBdlZJQ9LOsvxZ1bB0+GSzBHqPOuK7cj9JFEeUhhFpieq2Ra74ibjEnBIsVpVCRso254JfAKeR3RjToqYc/A7p+3G5cAQC3siiGlNpmCDA8DEVXmqJhIV0EWvlRIJG52koSbtsrvb8JboMB7u2k9fQ8kl/NTFJ29wnXQ+wVdyVDBb9KA5WKGYUxCzHLHJ5PGDqr/5OaOcshOmstTNt26DweP2P7d+NAFo15h7fmhSdaynKYJfIsvVI4Uzlevv7ydTJcmSx9ANNCVA7wQvAH5RlbFgch85gCTZCSSXO6Jg6q+pwU80buY+Vaf68c1nC4Lz2TeixT+yWn8Gz/g2TiZqVg25PbpfqOAxLRDfyrKMdy3AEYCVvEWoZGIsecmsRFFQ+GBvHu4oGobipCsGFDE="