# Remote Theme
remote_theme: mengyy212/minimal-light

# Site settings
title: Meng Yangyang
title_zh: 孟洋洋
# description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
avatar: /assets/img/avatar.jpg
favicon: /assets/img/avatar.png
favicon_dark: /assets/img/avatar.png

repository: mengyy212/mengyy212.github.io


# Personal Info
position: Postdoctoral Fellow
department: Department of Civil and Environmental Engineering
affiliation: The Hong Kong Polytechnic University (PolyU)
email: mengyy17@tsinghua.org.cn <br> yangyang.meng@polyu.edu.hk
# keywords: academic


# Social Links
google_scholar: https://scholar.google.com/citations?user=UiLNLpkAAAAJ
orcid: https://orcid.org/0000-0003-4386-1858
# github_link: https://github.com/yaoyao-liu/minimal-light
# linkedin: https://www.linkedin.com/
# canonical: https://minimal-light.yyliu.net/


# Analytics
google_analytics: "G-L5F2PF7KD9"
